version: "3.9"

services:
  backend:
    build: ./api_server
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    restart: always

networks:
  default:
    name: chatbot-network